"""empty message

Revision ID: 0c901606ca92
Revises: 5b9e11c0116f
Create Date: 2019-10-04 15:11:25.026575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c901606ca92'
down_revision = '5b9e11c0116f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_request', sa.Column('minimum_account_balance', sa.BigInteger(), nullable=False, comment="Determines the amount that must remain available on sender's account after the requested amount has been secured."))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_request', 'minimum_account_balance')
    # ### end Alembic commands ###
