"""empty message

Revision ID: 0f2786ad566d
Revises: bc43faae7a26
Create Date: 2019-05-05 15:12:35.338958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f2786ad566d'
down_revision = 'bc43faae7a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debtor_policy_change_signal')
    op.alter_column('account', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='Incremented on every change in `balance`, `concession_interest_rate`, `debtor_policy.interest_rate`, or `debtor_policy.interest_rate_floor`.',
               existing_comment='Incremented on every change in `balance` or `concession_interest_rate`.',
               existing_nullable=False)
    op.alter_column('account', 'last_change_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated on every increment of `last_change_seqnum`.',
               existing_comment='Updated on every change in `balance` or `concession_interest_rate`',
               existing_nullable=False)
    op.add_column('account_change_signal', sa.Column('interest_rate', sa.REAL(), nullable=False))
    op.add_column('account_change_signal', sa.Column('interest_rate_floor', sa.REAL(), nullable=False))
    op.drop_column('debtor_policy', 'last_change_ts')
    op.drop_column('debtor_policy', 'last_change_seqnum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtor_policy', sa.Column('last_change_seqnum', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('debtor_policy', sa.Column('last_change_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('account_change_signal', 'interest_rate_floor')
    op.drop_column('account_change_signal', 'interest_rate')
    op.alter_column('account', 'last_change_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated on every change in `balance` or `concession_interest_rate`',
               existing_comment='Updated on every increment of `last_change_seqnum`.',
               existing_nullable=False)
    op.alter_column('account', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='Incremented on every change in `balance` or `concession_interest_rate`.',
               existing_comment='Incremented on every change in `balance`, `concession_interest_rate`, `debtor_policy.interest_rate`, or `debtor_policy.interest_rate_floor`.',
               existing_nullable=False)
    op.create_table('debtor_policy_change_signal',
    sa.Column('debtor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('change_seqnum', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('change_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('interest_rate_floor', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'change_seqnum', name='debtor_policy_change_signal_pkey')
    )
    # ### end Alembic commands ###
