"""empty message

Revision ID: 15cee4ecef27
Revises: 8cfdea27d67f
Create Date: 2019-05-05 16:04:45.387076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15cee4ecef27'
down_revision = '8cfdea27d67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepared_circular_transfer_signal',
    sa.Column('coordinator_id', sa.BigInteger(), nullable=False),
    sa.Column('coordinator_transfer_request_id', sa.BigInteger(), nullable=False),
    sa.Column('prepared_transfer_seqnum', sa.BigInteger(), nullable=False),
    sa.Column('prepared_at_ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('coordinator_id', 'coordinator_transfer_request_id')
    )
    op.create_table('rejected_circular_transfer_signal',
    sa.Column('coordinator_id', sa.BigInteger(), nullable=False),
    sa.Column('coordinator_transfer_request_id', sa.BigInteger(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('coordinator_id', 'coordinator_transfer_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_circular_transfer_signal')
    op.drop_table('prepared_circular_transfer_signal')
    # ### end Alembic commands ###
