"""empty message

Revision ID: 1c9efb5e6329
Revises: bee08b0faf95
Create Date: 2019-07-30 21:23:15.327138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c9efb5e6329'
down_revision = 'bee08b0faf95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'attributes_last_change_seqnum',
               existing_type=sa.INTEGER(),
               comment='Updated on every change in account attributes (the `interest_rate` for example).',
               existing_nullable=True)
    op.alter_column('account', 'attributes_last_change_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated on every change in account attributes (the `interest_rate` for example).',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'attributes_last_change_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Updated on every change in account attributes (the `interest_rate` for example).',
               existing_nullable=True)
    op.alter_column('account', 'attributes_last_change_seqnum',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Updated on every change in account attributes (the `interest_rate` for example).',
               existing_nullable=True)
    # ### end Alembic commands ###
