"""empty message

Revision ID: 4f0d63b7a85c
Revises: bb3fb611516c
Create Date: 2019-05-06 15:47:35.353305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0d63b7a85c'
down_revision = 'bb3fb611516c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'sender_locked_amount',
               existing_type=sa.BIGINT(),
               comment='This amount has been subtracted from the available account balance.',
               existing_comment='This amount that has been subtracted from the available account balance.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'sender_locked_amount',
               existing_type=sa.BIGINT(),
               comment='This amount that has been subtracted from the available account balance.',
               existing_comment='This amount has been subtracted from the available account balance.',
               existing_nullable=False)
    # ### end Alembic commands ###
