"""empty message

Revision ID: 50eae8d00e44
Revises: 3d9f6e88032b
Create Date: 2019-07-29 20:58:05.836445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eae8d00e44'
down_revision = '3d9f6e88032b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committed_transfer_signal', 'committed_transfer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committed_transfer_signal', sa.Column('committed_transfer_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
