"""empty message

Revision ID: 550dccedb744
Revises: 02002f85eb64
Create Date: 2019-05-06 20:45:02.655084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550dccedb744'
down_revision = '02002f85eb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepared_transfer_signal', sa.Column('debtor_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepared_transfer_signal', 'debtor_id')
    # ### end Alembic commands ###
