"""empty message

Revision ID: 5e487e137ad8
Revises: 7f404147b60f
Create Date: 2019-05-06 17:25:13.627044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e487e137ad8'
down_revision = '7f404147b60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'avl_balance',
               existing_type=sa.BIGINT(),
               comment='The `balance` minus pending transfer locks',
               existing_comment='The `balance`, plus `interest`, minus pending transfer locks',
               existing_nullable=False)
    op.alter_column('account', 'concession_interest_rate',
               existing_type=sa.REAL(),
               comment='An interest rate exclusive for this account, presumably more advantageous for the account owner than the standard one. Interest accumulates at an annual rate (in percents) that is equal to the maximum of `concession_interest_rate` and `debtor_policy.interest_rate`.',
               existing_comment='An interest rate exclusive for this account, presumably more advantageous for the account owner than the standard one.',
               existing_nullable=False)
    op.alter_column('account', 'interest',
               existing_type=sa.BIGINT(),
               comment='The amount of interest accumulated on the account before `last_change_ts`, but not added to the `balance` yet. Can be a negative number. `interest`gets zeroed and added to the ballance one in while (like once per year).',
               existing_comment='The amount of interest accumulated on the account. Can be negative. Interest accumulates at an annual rate (in percents) that is equal to the maximum of `concession_interest_rate` and `debtor_policy.interest_rate`.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'interest',
               existing_type=sa.BIGINT(),
               comment='The amount of interest accumulated on the account. Can be negative. Interest accumulates at an annual rate (in percents) that is equal to the maximum of `concession_interest_rate` and `debtor_policy.interest_rate`.',
               existing_comment='The amount of interest accumulated on the account before `last_change_ts`, but not added to the `balance` yet. Can be a negative number. `interest`gets zeroed and added to the ballance one in while (like once per year).',
               existing_nullable=False)
    op.alter_column('account', 'concession_interest_rate',
               existing_type=sa.REAL(),
               comment='An interest rate exclusive for this account, presumably more advantageous for the account owner than the standard one.',
               existing_comment='An interest rate exclusive for this account, presumably more advantageous for the account owner than the standard one. Interest accumulates at an annual rate (in percents) that is equal to the maximum of `concession_interest_rate` and `debtor_policy.interest_rate`.',
               existing_nullable=False)
    op.alter_column('account', 'avl_balance',
               existing_type=sa.BIGINT(),
               comment='The `balance`, plus `interest`, minus pending transfer locks',
               existing_comment='The `balance` minus pending transfer locks',
               existing_nullable=False)
    # ### end Alembic commands ###
