"""empty message

Revision ID: 620ae0f24ecb
Revises: acde8af9190a
Create Date: 2019-07-17 22:51:58.160225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620ae0f24ecb'
down_revision = 'acde8af9190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_change', sa.Column('finalized_transfer_id', sa.BigInteger(), nullable=True))
    op.add_column('pending_change', sa.Column('unlocked_amount', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_change', 'unlocked_amount')
    op.drop_column('pending_change', 'finalized_transfer_id')
    # ### end Alembic commands ###
