"""empty message

Revision ID: 6c0ed9fba5cc
Revises: b45b896406d5
Create Date: 2019-06-05 23:48:11.465208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0ed9fba5cc'
down_revision = 'b45b896406d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_change_signal', sa.Column('last_transfer_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_change_signal', 'last_transfer_date')
    # ### end Alembic commands ###
