"""empty message

Revision ID: 7bc1d4681fe1
Revises: 5f87fd3ba0cb
Create Date: 2019-06-01 01:18:24.084454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc1d4681fe1'
down_revision = '5f87fd3ba0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('interest_rate_last_change_seqnum', sa.Integer(), nullable=True))
    op.add_column('account', sa.Column('interest_rate_last_change_ts', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'interest_rate_last_change_ts')
    op.drop_column('account', 'interest_rate_last_change_seqnum')
    # ### end Alembic commands ###
