"""empty message

Revision ID: 85945fe9c639
Revises: cd93dad7733d
Create Date: 2019-05-06 15:04:14.757552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85945fe9c639'
down_revision = 'cd93dad7733d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'concession_interest_rate',
               existing_type=sa.REAL(),
               comment='An interest rate exclusive for this account, presumably more advantageous for the account owner than the standard one.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'concession_interest_rate',
               existing_type=sa.REAL(),
               comment=None,
               existing_comment='An interest rate exclusive for this account, presumably more advantageous for the account owner than the standard one.',
               existing_nullable=False)
    # ### end Alembic commands ###
