"""empty message

Revision ID: 93d3b46ee657
Revises: a68526e3af68
Create Date: 2019-05-05 15:39:16.396796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d3b46ee657'
down_revision = 'a68526e3af68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committed_transfer_signal', sa.Column('committed_amount', sa.BigInteger(), nullable=False))
    op.drop_column('committed_transfer_signal', 'commited_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committed_transfer_signal', sa.Column('commited_amount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('committed_transfer_signal', 'committed_amount')
    # ### end Alembic commands ###
