"""empty message

Revision ID: 985bd683dfb7
Revises: 22e53dea1754
Create Date: 2019-05-04 23:20:20.863610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985bd683dfb7'
down_revision = '22e53dea1754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtor_policy_update_signal',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('last_change_seqnum', sa.BigInteger(), nullable=False),
    sa.Column('interest_rate', sa.REAL(), nullable=False),
    sa.Column('interest_rate_floor', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'last_change_seqnum')
    )
    op.drop_table('debtor_accounts_policy_update_signal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtor_accounts_policy_update_signal',
    sa.Column('debtor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_change_seqnum', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('interest_rate_floor', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'last_change_seqnum', name='debtor_accounts_policy_update_signal_pkey')
    )
    op.drop_table('debtor_policy_update_signal')
    # ### end Alembic commands ###
