"""empty message

Revision ID: a68526e3af68
Revises: 0f2786ad566d
Create Date: 2019-05-05 15:37:22.436513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68526e3af68'
down_revision = '0f2786ad566d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committed_transfer_signal', sa.Column('commited_amount', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committed_transfer_signal', 'commited_amount')
    # ### end Alembic commands ###
