"""empty message

Revision ID: af602a9c899a
Revises: b866c83f8c83
Create Date: 2019-05-05 00:46:20.736558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af602a9c899a'
down_revision = 'b866c83f8c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_change_signal',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('change_seqnum', sa.BigInteger(), nullable=False),
    sa.Column('change_ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('concession_interest_rate', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'creditor_id', 'change_seqnum')
    )
    op.create_table('debtor_policy_change_signal',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('change_seqnum', sa.BigInteger(), nullable=False),
    sa.Column('change_ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interest_rate', sa.REAL(), nullable=False),
    sa.Column('interest_rate_floor', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'change_seqnum')
    )
    op.drop_table('account_update_signal')
    op.drop_table('debtor_policy_update_signal')
    op.add_column('account', sa.Column('last_activity_ts', sa.TIMESTAMP(timezone=True), nullable=False, comment='Updated on every account activity. This is useful to remove stale accounts.'))
    op.alter_column('account', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='Incremented on every change in `balance` or `concession_interest_rate`. Zero indicates a stale account.',
               existing_comment='This is incremented on every change. Zero indicates a deactivated account.',
               existing_nullable=False)
    op.alter_column('account', 'last_change_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated on every change in `balance` or `concession_interest_rate`',
               existing_comment='This is updated on every change.',
               existing_nullable=False)
    op.add_column('debtor_policy', sa.Column('last_change_ts', sa.TIMESTAMP(timezone=True), nullable=False))
    op.alter_column('debtor_policy', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='This is incremented on every change. Zero indicates a deactivated debtor.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debtor_policy', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='This is incremented on every change. Zero indicates a deactivated debtor.',
               existing_nullable=False)
    op.drop_column('debtor_policy', 'last_change_ts')
    op.alter_column('account', 'last_change_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='This is updated on every change.',
               existing_comment='Updated on every change in `balance` or `concession_interest_rate`',
               existing_nullable=False)
    op.alter_column('account', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='This is incremented on every change. Zero indicates a deactivated account.',
               existing_comment='Incremented on every change in `balance` or `concession_interest_rate`. Zero indicates a stale account.',
               existing_nullable=False)
    op.drop_column('account', 'last_activity_ts')
    op.create_table('debtor_policy_update_signal',
    sa.Column('debtor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_change_seqnum', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('interest_rate_floor', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'last_change_seqnum', name='debtor_policy_update_signal_pkey')
    )
    op.create_table('account_update_signal',
    sa.Column('debtor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('creditor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_change_seqnum', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('concession_interest_rate', sa.REAL(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'creditor_id', 'last_change_seqnum', name='account_update_signal_pkey')
    )
    op.drop_table('debtor_policy_change_signal')
    op.drop_table('account_change_signal')
    # ### end Alembic commands ###
