"""empty message

Revision ID: b6eed1b23560
Revises: 1e84a69d5e80
Create Date: 2019-05-07 15:59:48.862339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eed1b23560'
down_revision = '1e84a69d5e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'transfer_id',
               existing_type=sa.BIGINT(),
               comment='Along with `debtor_id` and `sender_creditor_id` uniquely identifies a transfer',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'transfer_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Along with `debtor_id` and `sender_creditor_id` uniquely identifies a transfer',
               autoincrement=True)
    # ### end Alembic commands ###
