"""empty message

Revision ID: b82941eb06ac
Revises: dc66771a1d97
Create Date: 2019-05-15 12:43:30.239840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b82941eb06ac'
down_revision = 'dc66771a1d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_activity_date', sa.DATE(), nullable=False, comment='Updated on owner activity. Can be used to remove stale accounts.'))
    op.drop_column('account', 'last_activity_ts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_activity_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Updated on owner activity. Can be used to remove stale accounts.'))
    op.drop_column('account', 'last_activity_date')
    # ### end Alembic commands ###
