"""empty message

Revision ID: bb3fb611516c
Revises: 85945fe9c639
Create Date: 2019-05-06 15:41:00.648908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3fb611516c'
down_revision = '85945fe9c639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'amount',
               existing_type=sa.BIGINT(),
               comment='The actual transferred (committed) amount may not exceed this number.',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'coordinator_type',
               existing_type=sa.VARCHAR(length=30),
               comment='Indicates which subsystem has initiated the transfer and is responsible for finalizing it. The value must be a valid python identifier, all lowercase, no double underscores. Example: direct, circular.',
               existing_comment='Must be a valid python identifier. Example: direct, circular.',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'recipient_creditor_id',
               existing_type=sa.BIGINT(),
               comment='The payee',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'sender_creditor_id',
               existing_type=sa.BIGINT(),
               comment='The payer',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'sender_locked_amount',
               existing_type=sa.BIGINT(),
               comment='This amount that has been subtracted from the available account balance.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'sender_locked_amount',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='This amount that has been subtracted from the available account balance.',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'sender_creditor_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='The payer',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'recipient_creditor_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='The payee',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'coordinator_type',
               existing_type=sa.VARCHAR(length=30),
               comment='Must be a valid python identifier. Example: direct, circular.',
               existing_comment='Indicates which subsystem has initiated the transfer and is responsible for finalizing it. The value must be a valid python identifier, all lowercase, no double underscores. Example: direct, circular.',
               existing_nullable=False)
    op.alter_column('prepared_transfer', 'amount',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='The actual transferred (committed) amount may not exceed this number.',
               existing_nullable=False)
    # ### end Alembic commands ###
