"""empty message

Revision ID: bc43faae7a26
Revises: c1c9e81ad7e7
Create Date: 2019-05-05 01:06:00.606146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc43faae7a26'
down_revision = 'c1c9e81ad7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'last_activity_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated on every account activity. Can be used to remove stale accounts.',
               existing_comment='Updated on every account activity. This is useful to remove stale accounts.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'last_activity_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Updated on every account activity. This is useful to remove stale accounts.',
               existing_comment='Updated on every account activity. Can be used to remove stale accounts.',
               existing_nullable=False)
    # ### end Alembic commands ###
