"""empty message

Revision ID: c1c9e81ad7e7
Revises: af602a9c899a
Create Date: 2019-05-05 00:58:28.955481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c9e81ad7e7'
down_revision = 'af602a9c899a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='Incremented on every change in `balance` or `concession_interest_rate`.',
               existing_comment='Incremented on every change in `balance` or `concession_interest_rate`. Zero indicates a stale account.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'last_change_seqnum',
               existing_type=sa.BIGINT(),
               comment='Incremented on every change in `balance` or `concession_interest_rate`. Zero indicates a stale account.',
               existing_comment='Incremented on every change in `balance` or `concession_interest_rate`.',
               existing_nullable=False)
    # ### end Alembic commands ###
