"""empty message

Revision ID: cf4770f65652
Revises: 3282f7e100aa
Create Date: 2019-05-05 16:50:54.414539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf4770f65652'
down_revision = '3282f7e100aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_circular_transfer_signal')
    op.add_column('prepared_circular_transfer_signal', sa.Column('prepared_amount', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepared_circular_transfer_signal', 'prepared_amount')
    op.create_table('rejected_circular_transfer_signal',
    sa.Column('coordinator_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('coordinator_transfer_request_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('coordinator_id', 'coordinator_transfer_request_id', name='rejected_circular_transfer_signal_pkey')
    )
    # ### end Alembic commands ###
