"""empty message

Revision ID: d79c2e4a345e
Revises: 475c15a40c10
Create Date: 2020-01-31 19:45:58.498017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79c2e4a345e'
down_revision = '475c15a40c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepared_transfer', sa.Column('coordinator_id', sa.BigInteger(), nullable=False))
    op.add_column('prepared_transfer', sa.Column('coordinator_request_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepared_transfer', 'coordinator_request_id')
    op.drop_column('prepared_transfer', 'coordinator_id')
    # ### end Alembic commands ###
