"""empty message

Revision ID: e75a134e0a7c
Revises: 4ec1e2162731
Create Date: 2019-05-14 02:22:34.539762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75a134e0a7c'
down_revision = '4ec1e2162731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'sender_locked_amount',
               existing_type=sa.BIGINT(),
               comment='This amount has been added to `sender_account.locked_amount`.',
               existing_comment='This amount has been added to `account.locked_amount`.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'sender_locked_amount',
               existing_type=sa.BIGINT(),
               comment='This amount has been added to `account.locked_amount`.',
               existing_comment='This amount has been added to `sender_account.locked_amount`.',
               existing_nullable=False)
    # ### end Alembic commands ###
