"""empty message

Revision ID: f36d2dfe2789
Revises: 8b61256f5488
Create Date: 2020-02-03 17:43:31.282798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f36d2dfe2789'
down_revision = '8b61256f5488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('last_remainder_ts', sa.TIMESTAMP(timezone=True), nullable=False, comment='The moment at which the last `AccountChangeSignal` was sent to remaind that the account still exists. This column helps to prevent sending remainders too often.'))
    op.alter_column('prepared_transfer', 'last_remainder_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='The moment at which the last `PreparedTransferSignal` was sent to remaind that the prepared transfer must be finalized. A `NULL` means that no remainders have been sent yet. This column helps to prevent sending remainders too often.',
               existing_comment='The moment at which the last `PreparedTransferSignal` was sent as a remainder that the prepared transfer waits to be finalized. A `NULL` means that no remainders have been sent yet. This column helps to prevent sending remainders too often.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prepared_transfer', 'last_remainder_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='The moment at which the last `PreparedTransferSignal` was sent as a remainder that the prepared transfer waits to be finalized. A `NULL` means that no remainders have been sent yet. This column helps to prevent sending remainders too often.',
               existing_comment='The moment at which the last `PreparedTransferSignal` was sent to remaind that the prepared transfer must be finalized. A `NULL` means that no remainders have been sent yet. This column helps to prevent sending remainders too often.',
               existing_nullable=True)
    op.drop_column('account', 'last_remainder_ts')
    # ### end Alembic commands ###
