"""empty message

Revision ID: f3c21e0545d2
Revises: acde8af9190a
Create Date: 2019-07-18 02:42:49.599350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c21e0545d2'
down_revision = 'acde8af9190a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_change', sa.Column('unlocked_amount', sa.BigInteger(), nullable=True, comment='If not NULL, the value must be subtracted from `account.locked_amount`, and `account.prepared_transfers_count` must be decremented.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_change', 'unlocked_amount')
    # ### end Alembic commands ###
