"""empty message

Revision ID: f6e0ff8ee775
Revises: bbcd77f71465
Create Date: 2024-05-11 20:14:34.353839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e0ff8ee775'
down_revision = 'bbcd77f71465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepared_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('min_interest_rate')

    with op.batch_alter_table('prepared_transfer_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('min_interest_rate')

    with op.batch_alter_table('transfer_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.drop_column('min_interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_interest_rate', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_column('final_interest_rate_ts')

    with op.batch_alter_table('prepared_transfer_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_interest_rate', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_column('final_interest_rate_ts')

    with op.batch_alter_table('prepared_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_interest_rate', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_column('final_interest_rate_ts')

    # ### end Alembic commands ###
